### ISSUE TITLE
pre-commit hook fails when adding args

### ISSUE THREAD

**Issue by sanzoghenzo** [jorisroovers/gitlint#109]
Hi,
I just found this great project and I would like to use it with pre-commit to enforce conventional commit style messages.

I've set up my `.pre-commit-config.yml` like this:

```yml
default_stages: [commit, push]
repos:
  # many other commit hooks here...
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
    -   id: gitlint
        stages: [commit-msg]
        args: [--contrib=CT1]
```

and correctly installed the hooks.

When I try to commit something, I get

```
gitlint..................................................................Failed
hookid: gitlint

Usage: gitlint [OPTIONS] COMMAND [ARGS]...
Try "gitlint --help" for help.

Error: Invalid value for "--msg-filename": Could not open file: --contrib=CT1: No such file or directory
```

This is because of how [arguments are passed by pre-commit](https://pre-commit.com/#arguments-pattern-in-hooks).

The workaround is overriding the hook entry and putting --msg-filename at the end of the args:

```yml
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
    -   id: gitlint
        stages: [commit-msg]
        entry: gitlint
        args: [--contrib=CT1, --msg-filename]
```

Not sure how it can be solved without major changes involving passing the commit file as positional argument.
