### ISSUE TITLE
BUG: if used with pre-commit and additional args -> Invalid value for "--msg-filename"

### ISSUE THREAD

**Issue by Cielquan** [jorisroovers/gitlint#163]
When I use gitlint with pre-commit and want to add `--extra-path` for custom rules like so:

```yaml
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: c359748723a52f6c0c5f87c3b71749f75179ca74  # frozen: v0.14.0
    hooks:
      - id: gitlint
        args: [--extra-path pre-commit-helper.py]
```

I get the error:

```console
gitlint..................................................................Failed
- hook id: gitlint
- exit code: 253

Usage: gitlint [OPTIONS] COMMAND [ARGS]...
Try "gitlint --help" for help.

Error: Invalid value for "--msg-filename": Could not open file: --extra-path pre-commit-helper.py: No such file or directory

*** Exit Code: 1 ***
```

Reason for this is that my added args `[--extra-path pre-commit-helper.py]` are appended to the end after the entry-point. In gitlint's `.pre-commit-hooks.yaml` the entry contains args and `--msg-filename` as one expects a value to follow.

As a workaround you have to overwrite the entry in `.pre-commit-config.yaml` like so:

```yaml
  - repo: https://github.com/jorisroovers/gitlint
    rev: c359748723a52f6c0c5f87c3b71749f75179ca74  # frozen: v0.14.0
    hooks:
      - id: gitlint
        entry: gitlint
        args: [--extra-path, pre-commit-helper.py, --staged, --msg-filename]
```

As a fix you have to move the args from `entry` to `args`. I will submit a PR.
Sure you then have to specify them again, if you overwrite them, but that gives you more granular control as a user and its cleaner IMHO.
