### ISSUE TITLE
Usage with `pre-commit`

### ISSUE THREAD

**Issue by sobolevn** [jorisroovers/gitlint#38]
Hi, thanks for this package!

I have a question: what is the best way to integrate this library with http://pre-commit.com/ ?
Thanks!

**Comment by asottile** [comment]
The interface for pre-commit is to pass a single argument on the commandline that is the commit-msg filename.  It seems that gitlint doesn't have an interface which enables this -- I'll see if I can't craft a PR.

A workaround would be to use the interface that gitlint uses in its hook file, something like this:

```yaml
-   id: gitlint
    name: gitlint
    language: python
    entry: bash -c 'cat "$@" | python -m gitlint.cli' --
    stages: [commit-msg]
```
