### ISSUE TITLE
Poetry version solving failure

### ISSUE THREAD

**Issue by borolepratik** [jorisroovers/gitlint#538]
```toml
[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.0"
fastf1 = "^3.2.0"
uvicorn = { extras = ["standard"], version = "^0.26.0" }

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
isort = "^5.13.2"
jupyterlab = "^4.0.11"
jupyterlab-code-formatter = "^2.2.1"
pytest = "^7.4.4"
httpx = "^0.26.0"
commitizen = "^3.13.0"
poetry-githooks = "^3.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.githooks]
pre-commit = "gitlint"
```

poetry version solving fails when i run `poetry add gitlint --group dev`

Error:
```
Because no versions of gitlint match >0.19.1,<0.19.2.dev1 || >0.19.2.dev1,<0.19.2.dev2 || >0.19.2.dev2,<0.19.2.dev3 || >0.19.2.dev3,<0.19.2.dev4 || >0.19.2.dev4,<0.19.2.dev5 || >0.19.2.dev5,<0.20.0
 and gitlint (0.19.2.dev1) depends on gitlint-core (0.19.2.dev1), gitlint (>0.19.1,<0.19.2.dev2 || >0.19.2.dev2,<0.19.2.dev3 || >0.19.2.dev3,<0.19.2.dev4 || >0.19.2.dev4,<0.19.2.dev5 || >0.19.2.dev5,<0.20.0) requires gitlint-core (0.19.2.dev1).
And because gitlint-core (0.19.2.dev1) depends on click (8.1.3), gitlint (>0.19.1,<0.19.2.dev2 || >0.19.2.dev2,<0.19.2.dev3 || >0.19.2.dev3,<0.19.2.dev4 || >0.19.2.dev4,<0.19.2.dev5 || >0.19.2.dev5,<0.20.0) requires click (8.1.3).
And because gitlint (0.19.2.dev2) depends on gitlint-core (0.19.2.dev2)
 and gitlint-core (0.19.2.dev2) depends on click (8.1.3), gitlint (>0.19.1,<0.19.2.dev3 || >0.19.2.dev3,<0.19.2.dev4 || >0.19.2.dev4,<0.19.2.dev5 || >0.19.2.dev5,<0.20.0) requires click (8.1.3).
And because gitlint (0.19.2.dev4) depends on gitlint-core (0.19.2.dev4)
 and gitlint-core (0.19.2.dev4) depends on click (8.1.3), gitlint (>0.19.1,<0.19.2.dev5 || >0.19.2.dev5,<0.20.0) requires click (8.1.3).
And because gitlint (0.19.2.dev5) depends on gitlint-core (0.19.2.dev5)
 and gitlint-core (0.19.2.dev5) depends on click (8.1.3), gitlint (>0.19.1,<0.20.0) requires click (8.1.3).
And because gitlint (0.19.1) depends on gitlint-core (0.19.1)
 and gitlint-core (0.19.1) depends on click (8.1.3), gitlint (>=0.19.1,<0.20.0) requires click (8.1.3).
And because poetry-githooks (3.0.1) depends on click (>=8.1.6,<9.0.0)
 and no versions of poetry-githooks match >3.0.1,<4.0.0, gitlint (>=0.19.1,<0.20.0) is incompatible with poetry-githooks (>=3.0.1,<4.0.0).
So, because backend depends on both poetry-githooks (^3.0.1) and gitlint (^0.19.1), version solving failed.
```
