### ISSUE TITLE
Remove interaction "Continue with commit anyways"

### ISSUE THREAD

**Issue by ootkin** [jorisroovers/gitlint#557]
Hi,

is it possible to remove the CLI interaction "Continue with commit anyways".

if the commit contains violations i dont want have the possibility to continue with the commit.

Thanks!

```sh
git commit -m "invalid commit"
gitlint: checking commit message...
1: CT1 Title does not follow ConventionalCommits.org format 'type(optional-scope): description': "invalid commit"
-----------------------------------------------
gitlint: Your commit message contains violations.
Continue with commit anyways (this keeps the current commit message)? [y(es)/n(no)/e(dit)]
````

.pre-commit-config.yaml
```yaml
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
````

.gitlint
```txt
[general]
# You HAVE to add the rule to [general] to enable it
# Only configuring (such as below) does NOT enable it.
contrib = contrib-title-conventional-commits

ignore=B6

[contrib-title-conventional-commits]
types=fix,feat,chore,docs,style,refactor,perf,test,revert,ci,build
```
