### ISSUE TITLE
work with pre-commit

### ISSUE THREAD

**Issue by xsteadfastx** [jorisroovers/gitlint#67]
i really like the gitlint program and i would love to use it in my pre-commit chain. i configured it like in the docs. i just dont get it how it works. how can it check the commit message if its tested pre-commit? do i need to add the commit message to a txt file?

**Comment by jumanjiman** [comment]
@xsteadfastx 

Here's how i use gitlint with pre-commit:
* https://github.com/jumanjihouse/autostager/commit/f50e61533ceb7d73abe00c2049a4e89f67baf38b
* https://github.com/jumanjihouse/docker-rsyslog/commit/3679763aebbd3b99f5669a8996fc3946051f2e45

This allows it to work both as the pre-commit hook and as part of CI.

**Comment by xsteadfastx** [comment]
@jumanjiman does i understand it right that the magic is the stages: commit-msg does the magic?

**Comment by xsteadfastx** [comment]
that does exactly nothing in my case... tried it with `git commit`... my vim opens, i add my message and it commits without gitlint checking it.

in my config:

```
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.10.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=88, --safe]
        python_version: python3.6

```
