### ISSUE TITLE
Pre-commit: No hook with id `gitlint`

### ISSUE THREAD

**Issue by akakoori** [jorisroovers/gitlint#86]
Installed gitlint with pre-commit following the doc, and it doesn't work.
```bash
(py37) ➜  workspace git:(develop) ✗ git commit -m 'testlkasdklnalgklkwamglamweoingienibgblalsjkdlgjldjlgasdgfasdfasdfasdgwebbffsdfsdnsdfsgwrqwrqwr'
autopep8.................................................................Passed
Check for added large files..............................................Passed
Check JSON...............................................................Passed
Check for merge conflicts................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Flake8...................................................................Passed
Fix requirements.txt.....................................................Passed
Don't commit to branch...................................................Passed
Trim Trailing Whitespace.................................................Passed
[develop (root-commit) 8ae7eec] testlkasdklnalgklkwamglamweoingienibgblalsjkdlgjldjlgasdgfasdfasdfasdgwebbffsdfsdnsdfsgwrqwrqwr
 17 files changed, 825 insertions(+)
```

When run `pre-commit run gitlint`, I got:
```bash
No hook with id `gitlint`
```
Here is my `.pre-commit-config.yaml`:
```yaml
repos:

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args:
        - --in-place
        - --ignore=E501

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: flake8
        args:
        - --extend-ignore=E501
    -   id: requirements-txt-fixer
        files: requirements*
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md

-   repo: https://github.com/jorisroovers/gitlint
    rev:  master
    hooks:
    -   id: gitlint
 
```

**Comment by esciara** [comment]
Same issue with:
```
repos:
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.11.0
    hooks:
      -   id: gitlint
```

Any idea of where it could come from?

**Comment by jorisroovers** [comment]
I had a look at this and can reproduce. I haven't really used pre-commit myself before this occasion, so not sure how exactly it worked before. I also can't immediately figure out what's wrong either.

@asottile can you chime in?

CC: @retr0h

**Comment by asottile** [comment]
You need `pre-commit install --hook-type commit-msg` for pre-commit to run on the `commit-msg` stage.  By default `pre-commit install` will only install `.git/hooks/pre-commit`

The reason `pre-commit run gitlint` fails with a "No hook with id ..." message is because it's running in "pre-commit hook" mode (as opposed to "commit-msg hook" mode)

Here's an example invocation from `pre-commit run`:

```console
$ cat .git/COMMIT_EDITMSG 
hi
$ pre-commit run gitlint --hook-stage commit-msg --commit-msg-filename .git/COMMIT_EDITMSG 
gitlint..................................................................Failed
hookid: gitlint

3: B6 Body message is missing

```

**Comment by retr0h** [comment]
@asottile do I need to run both `pre-commit install --hook-type commit-msg` and `pre-commit install `?

I notice hooks run twice when adding commit-msg hook.

```
black................................................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Detect secrets...........................................................Passed
gitblack................................................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Detect secrets...........................................................Passed
gitlint..................................................................Passed
```

**Comment by asottile** [comment]
ah yeah so by default hooks will be configured for all stages

there's a new setting in pre-comit `default_stages` which can probably help you out here -- something like `default_stages: [commit]` maybe?

**Comment by asottile** [comment]
oh yeah, and that setting is a [top level setting](https://pre-commit.com/#pre-commit-configyaml---top-level)

**Comment by esciara** [comment]
Rah, you beat me to it @asottile ...

Yes, I could reproduce and `default_stages: [commit]` is necessary and solves the redundancy. And actually, would that not be a better default than an "all stages" default?

**Comment by asottile** [comment]
most of the time it doesn't hurt to run-and-skip the other hooks :man_shrugging: -- defaulting to `default_stages: [commit]` would also break anyone using _just_ `pre-push`

it's also a bit of an unfortunate history as well -- the original tool wasn't ever going to support other hooks outside of `pre-commit`, `push`, `commit-msg`, and `prepare-commit-msg` were an afterthought :man_shrugging:

**Comment by esciara** [comment]
Maybe clarifying the docs, then?

**Comment by asottile** [comment]
happily would take suggestions on how to [expand the section on `stages`](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) :D  -- the source is https://github.com/pre-commit/pre-commit.github.io

**Comment by esciara** [comment]
@asottile : done 😜

**Comment by esciara** [comment]
@retr0h to avoid the pb, you need to set the top-level property `default_changes` to whatever stages your want to, probably the `commit` stage:
```yaml
default_stages: [commit]
...
- repo: https://github.com/jorisroovers/gitlint
  rev: master
  hooks:
    - id: gitlint
      name: gitlint
      language: python
      entry: gitlint --msg-filename
      stages: [commit-msg]
```
Or you could set for each hook the specific stage you want it to be installed in.

**Comment by asottile** [comment]
fortunately `gitlint` sets most of those things for you so you can do something like:

```yaml
default_stages: [commit]
# ...
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.11.0
  hooks:
    - id: gitlint
```

**Comment by esciara** [comment]
Errr... I thought the [`.pre-commit-hooks.yaml` file](https://github.com/jorisroovers/gitlint/blob/e16f01bd9026e5fe75a2631ac9df15f7ecea05f8/.pre-commit-hooks.yaml) was all wrong:

```yaml
-   id: gitlint
    name: gitlint
    language: python
    entry: gitlint --msg-filename
    stages: [commit-msg]
```

The [new hooks section](https://pre-commit.com/#new-hooks) of the doc does not have any mention of the `stages` property in a `.pre-commit-hooks.yaml` file... needs adding too?
